language: python

dist: jammy

sudo: required

install:
  - sudo apt update && sudo apt install shellcheck
  - bash scripts/set_up_python.sh

scripts:
  - make check-scripts

notifications:
  email: true
