language: python

dist: jammy

sudo: required

python:
  - "3.10"

env:
  global:
    - MICROMAMBA_VERSION=2.0.5-0

install:
  - sudo apt update && sudo apt install shellcheck
  - bash scripts/set_up_python.sh

scripts:
  - make check-scripts

notifications:
  email: true
